---
- name: Pull Create and Start container
  hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: Reddit-App
    default_container_image: rossarioagro/otus-reddit:1.0
  tasks:
    - name: Create containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        #state: present
        ports:
          - 9292:9292
        detach: true
      with_sequence: count={{ container_count }}
