version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - "post_db"
          - "comment_db"
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT_IN}:${UI_PORT_OUT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      front_net:
        aliases:
          - "post"
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_TAG}
    networks:
      back_net:
        aliases:
          - "comment"
      front_net:
        aliases:
          - "comment"

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
